### ISSUE TITLE
Support google_storage_bucket_object export

### ISSUE THREAD

**Issue by CelsoSantos** [GoogleCloudPlatform/terraformer#1065]
While the information already exported from GCS is very useful, it would also be useful to be able to replicate/export the directory and file "tree" ("tree" as we know that GCS is actually a flat filesystem).

Can this capability be added? Does it make sense?

**Comment by georgewilliamherbert** [comment]
Generically, all of the objects' contents data isn't backed up by the tool.  Disks aren't dumped or archived, storage buckets aren't copied or dumped, message queues aren't read, databases aren't dumped, etc.

I can see why you'd want that, but terraform usually doesn't provision contents like that and terraformer seems by design not to back them up.  You'd want to combine a backup tool for the objects' contents, and terraformer to ensure that the objects are all recreated so that you can restore their contents.

Perhaps a way to do full object data dumps would make sense as an extension or fork of Terraformer, so that it would be all in one.  But it's a slightly different problem.  And brings into play all the backup software issues (incremental vs full backups, size of backups and storage management, frozen point in time snapshot or rolling backup with possible time inconsistency across objects, ability to restore individual objects or sets of objects vs full restore, etc etc.).
