### ISSUE TITLE
AWS "ebs_block_device.0.volume_id": this field cannot be set

### ISSUE THREAD

**Issue by jalbstmeijer** [GoogleCloudPlatform/terraformer#130]
Using;

terraform 0.11.14
provider.aws 2.18.0
terraformer 0.7.5

The state output of the AWS ec2_instance import includes "volume_id" for "ebs_block_device.

When running "terraform plan" on that, I get;

Error: aws_instance.i-xxxx: "ebs_block_device.0.volume_id": this field cannot be set

Commenting the "volume_id" fixes the error.

**Comment by meshuga** [comment]
To refer the Terraform docs (https://www.terraform.io/docs/providers/aws/r/instance.html):
_Currently, changes to the ebs_block_device configuration of existing resources cannot be automatically detected by Terraform. To manage changes and attachments of an EBS block to an instance, use the aws_ebs_volume and aws_volume_attachment resources instead._

Currently each change in the EBS results in replacement of the device, which is not acceptable, a user risks data loss.

I think to best handle this issue is to refactor the code to make use of _aws_ebs_volume_ and _aws_volume_attachment_.
