### ISSUE TITLE
set ARM_SUBSCRIPTION_ID env var

### ISSUE THREAD

**Issue by smonda41** [GoogleCloudPlatform/terraformer#1586]
I am using Terraformer for importing existing infrastructure in azure. But whenever I am running the following command I am getting this error. Please anyone help. 
>terraformer import azure -r resource_group
>2022/12/06 22:38:29 set ARM_SUBSCRIPTION_ID env var
![Screenshot (102)](https://user-images.githubusercontent.com/119872331/205980918-d07fda02-9ab9-4964-a6b1-0ce41834991a.png)

**Comment by C0deR00kie** [comment]
It is the way terraformer works. Knowledge of the subscription id is required, due to multiple authentication methods, simply relying on az cli does not cover all usage scenarios.

`$Env:AMR_SUBSCRIPTION_ID=((az account show) | ConvertFrom-Json).id` would set the variable, this is powershell syntax, you could go either with PS/PS Core (if on linux), or adopt this solution for bash.
