### ISSUE TITLE
Gitlab provider: Incompatible API version with plugin. Plugin version: 6, Client versions: [5]

### ISSUE THREAD

**Issue by onjen** [GoogleCloudPlatform/terraformer#1778]
```
Incompatible API version with plugin. Plugin version: 6, Client versions: [5]
```
```
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v16.3.0
```

**Comment by o6uoq** [comment]
Pinning Cloudflare Terraform provider to `3.32.0` and no more recent worked for me.

This is due to [this commit](https://github.com/cloudflare/terraform-provider-cloudflare/commit/3a29e1cbd69b5dc49b986bcffb8846d831901a88#), explictly [this line](https://github.com/cloudflare/terraform-provider-cloudflare/commit/3a29e1cbd69b5dc49b986bcffb8846d831901a88#diff-004c813871d941da9fbaa8c8461a82be696a885962bcf366161c18f9b0cf1545R4).
