### ISSUE TITLE
aws envConfig AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY not being recognized

### ISSUE THREAD

**Issue by hotdawg789** [GoogleCloudPlatform/terraformer#188]
Running terraformer inside docker on ec2, the environment variables are not being given priority order.  Whats happening is the  Amazon EC2 instance, IAM role for Amazon EC2 instance is being used instead. 

I pass into docker run -e  AWS_SECRET_ACCESS_KEY=xxx -e AWS_ACCESS_KEY_ID=xxxx -e AWS_SESSION_TOKEN=xxxx at run time and assign terraformer as entrypoint in my dockerfile.  However when terraformer executes the EC2 instance IAM role credentials are being used and NOT the environment variables passed in.

According to AWS docs for go sdk the  default credential provider chain to find AWS credentials is: 
1)Environment variables.
2) Shared credentials file.
3) If your application is running on an Amazon EC2 instance, IAM role for Amazon EC2. https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html

However this doesn't appear to be the case for me.

**Comment by sergeylanzman** [comment]
I see in code terraformer override env params
here https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/aws_service.go#L38-L40

@meshuga Can you please write why we need this?

**Comment by meshuga** [comment]
It's needed in a case when a user provides credentials with MFA requirement since TF itself is unable to handle this case. I think it's too naive solution and should be improved although can't see why it would affect the order of credential provider chain.

I'd need to recreate the scenario and debug it but for now I added a small _adjustment_ - now shared config state is driven by env variable (https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/aws_service.go#L34), that could cause misbehaviour described in the issue. More info: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/sessions.html#creating-sessions

**Comment by mohag** [comment]
In current versions, you need to pass `--profile=` to get it to work with the env vars.
