### ISSUE TITLE
Option to import all of a provider's resources

### ISSUE THREAD

**Issue by aqche** [GoogleCloudPlatform/terraformer#233]
When trying to import all resources from a provider a user would have to type:
```
terraformer import <provider> --resources=<resource_1>,<resource_2>,...,<resource_N>
```
Perhaps it would be helpful to have a flag such as `--all`/`--all-resources` or the ability to pass in an argument to `--resources` such as `*` or `all` to allow users to import all resources available to a provider. Thoughts?

**Comment by meshuga** [comment]
In case of AWS it might not be best idea because of bigger number of IAM resources. I think if we'd want to introduce ability to import all resources, would be good to specify what resource groups we don't want to import.

Maybe what we could have is selective resource import, that is if a user would want to import a resource, connected resources would be fetched as well? In that way we'd make the import process quite fast.

**Comment by sergeylanzman** [comment]
You can replace `--all` with `terraformer import google -r $(terraformer import google list | grep -v NO_NEED_RESOURCES | xargs (Add here linux/max magic for ",")) --project=my-project`

**Comment by n1nj4-r4cc00n** [comment]
Thanks, @sergeylanzman , in case someone is looking for the exact command this is how I did it:

` terraformer import okta -r $(terraformer import okta list  | xargs | sed 's/ /,/g')` as you can see I only added the `sed` command to the above

**Comment by ldnicolasmay** [comment]
`--resources="*"` will do the trick. See here: https://github.com/GoogleCloudPlatform/terraformer#resources
