### ISSUE TITLE
Unable to Apply Imported AWS Security Groups due to Cycle

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [GoogleCloudPlatform/terraformer#275]
Currently AWS Security Group are imported in its standalone form with inline ingresses and egresses, due to that not always the imported resources are applicable.

Terraform has `aws_security_group_rule` resource that could be used instead of inlined rules to avoid this problem.

**Comment by sergeylanzman** [comment]
I know this issue, but `aws_security_group_rule` it's very ugly solution for many groups.
aws provider send API request for each rule.....

**Comment by t0rr3sp3dr0** [comment]
I've tried to parse the generated HCL and extract the ingresses and egresses to `aws_security_group_rule`s but I've failed. But even if I had succeeded the `terraform.tfstate` file would still be the inlined form and I don't know it's feasible to do that on this file as well.

**Comment by meshuga** [comment]
Let’s then compute a spanning tree and only create rules on edges

**Comment by RobertoUa** [comment]
Is it possible to force terraformer to import `aws_security_group_rule` instead of inlined?
We need this because you can't use both `aws_security_group` and `aws_security_group_rule`. For instance, we have `aws_security_group` in one module, but we add rules (`aws_security_group_rule`) in others.
Changing it manually after an import is tedious.

**Comment by t0rr3sp3dr0** [comment]
@RobertoUa, you should file another issue for that
