### ISSUE TITLE
Verbose / Debug

### ISSUE THREAD

**Issue by SantiEich** [GoogleCloudPlatform/terraformer#290]
➜  imports terraformer import newrelic -r alert     
2019/11/18 15:47:41 newrelic importing... alert
2019/11/18 15:47:52 json: invalid use of ,string struct tag, trying to unmarshal ".9" into float64

I have this problem and I can't solve it. I could put it in debug mode? TF_LOG=TRACE?

**Comment by pgrefviau** [comment]
Having the same problem here. Also with the NewRelic plugin. I've used the releases link to install terraformer, might try to build locally next to see if this changes anything.

**Comment by ntkach** [comment]
I have the same problem even using a downloaded release.

**Comment by ntkach** [comment]
For what it's worth, it seems to be something that only happens on the alert resources.

**Comment by pgrefviau** [comment]
The problem seems to originate from the `paultyng/go-newrelic` package. It looks as if the underlying issue with parsing floats was resolved [back in December](https://github.com/paultyng/go-newrelic/pull/81), and released as part of [version 4.10.0](https://github.com/paultyng/go-newrelic/releases/tag/v4.10.0).

Would it be possible to bump up the version of the dependency on  `paultyng/go-newrelic` to at least v4.10.0? I can open a MR with what I assume to be the necessary changes (i.e. editing the relevant entry in go.mod), but I'm not all too familiar with Go or with the contribution process for this codebase, so if anyone wants to help validate this or simply merge the fix in themselves, that'd be great.
