### ISSUE TITLE
Your --filter doesn't work

### ISSUE THREAD

**Issue by ssanbeg** [GoogleCloudPlatform/terraformer#331]
terraformer plan datadog --resources=monitor --filter=tag=xxxxxx pulls in all monitors. So does terraformer plan datadog --resources=monitor --filter=tag=xxxxxx;title=blah as does terraformer plan datadog --resources=monitor --filter=tag=xxxxxx:title=blah and terraformer plan datadog --resources=monitor --filter=tag=xxxxxx:'title:blah'

**Comment by meshuga** [comment]
The command `terraformer plan datadog --resources=monitor --filter=tag=xxxxxx` will try to filter resources with id `xxxxxx` from resource group `tag`, which you didn't ask for, so that's why you get all resources from `monitor` resource group. That's a basic filtering functionality described in [1].

If you want to filter resources by an attribute, you can try attribute filters, explained in [2]. The command `terraformer plan datadog --resources=monitor --filter=Name=tag;Value=xxxxxx` will filter out all fetched resources and leave only ones with field `tags` equal to `xxxxxx` or array field `tags` that contains value `xxxxxx`. That option is explained in AWS section and is requiring AWS-style of defining filters, which might be not aligned with all other providers but should work without bigger issues.

[1] https://github.com/GoogleCloudPlatform/terraformer#filtering
[2] https://github.com/GoogleCloudPlatform/terraformer#attribute-filters

**Comment by ssanbeg** [comment]
Clearly I did not understand the docs well enough. Perhaps describe that there too?

I have adjusted the pattern to match yours and the results are the same. Nothing is being filtered out.

Terraform v0.12.18
+ provider.azurerm v1.39.0
+ provider.datadog v2.5.0

**Comment by almoore** [comment]
I am having a similar issue with the latest version installed `0.8.5`. 
I try and import aws resources. When it comes to the `ec2_instances`, `cloudformation`, `subnets` it imports everything.

I use the following:
```
terraformer import aws --regions us-east-1 --profile xxxx -- --filter=aws_vpc=vpc-xxxxx \
  --resources alb,auto_scaling,cloudformation,dynamodb,ec2_instance,eip,ecs,elb,glue,iam,rds,route53,route_table,s3,sg,subnet,vpc,vpc_peering
```

**Comment by ssanbeg** [comment]
For anyone that happens to read this thread, I will assume you're using something like bash or zsh. I solved this the long way:

ids=$(curl -X GET -H "DD-API-KEY: ${DATADOG_API_KEY}" \
                               -H "DD-APPLICATION-KEY: ${DATADOG_APP_KEY}" \
                               'https://api.datadoghq.com/api/v1/monitor/search?query=word&per_page=1000' \
                               | jq '.monitors[] .id' \
);

for id in $ids; do
  terraformer import datadog -p $work_path/monitor-$id --resources=monitor --filter=datadog_monitor="${id}"
# followed by the 'sed' and 'grep' work 
lcwords=$(grep -E -m 1 'name.*=' $work_path/monitor-$id/monitor.tf)
...

**Comment by meshuga** [comment]
@ssanbeg 
To answer your concern, you can filter any resource by its resulting Terraform resource attributes. An example of an AWS resource [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html):
```
resource "aws_lambda_function" "lambda_function_id" {
  environment {
    variables = {
      SCHEDULE_HOURS = "1"
    }
  }
  runtime = "java8"
  tags = {
    "lambda:createdBy" = "SAM"
  }
 ...
}
```
To get only that Lambda function, you can issue the following commands:

- `terraformer import  aws --resources=lambda --filter="Name=environment.variables.SCHEDULE_HOURS;Value=1" --regions=ap-southeast-1 ` - to filter all resources by nested path
- `terraformer import  aws --resources=lambda --filter="Name=runtime;Value=java8" --regions=ap-southeast-1 ` - to filter all resources by simple path
- `terraformer import  aws --resources=lambda --filter=aws_lambda_function=lambda_function_id --regions=ap-southeast-1` - to filter `aws_lambda_function` resources by its id

This is still an example with AWS provider but that's the only environment I work with although the filtering logic is common for all providers (I don't want to setup my own personal Azure/DataDog accounts, would be nice if @Azure or @DataDog could provide such account with that since it's good for them).

@almoore 
Let me explain what the command you provided does. If you issue:
```
terraformer import aws --regions us-east-1 --profile xxxx --filter=aws_vpc=vpc-xxxxx \
  --resources alb,auto_scaling,cloudformation,dynamodb,ec2_instance,eip,ecs,elb,glue,iam,rds,route53,route_table,s3,sg,subnet,vpc,vpc_peering
```
You will import `alb,auto_scaling,cloudformation,dynamodb,ec2_instance,eip,ecs,elb,glue,iam,rds,route53,route_table,s3,sg,subnet,vpc,vpc_peering` resource groups and a filter for Terraform resource [aws_vpc](https://www.terraform.io/docs/providers/aws/r/vpc.html) with id `vpc-xxxxx` will be applied for `vpc` resource group **only**.
That's the caveat of this kind of simple filter and it's also something I don't much like but I don't think it's a good idea to introduce a breaking change to this functionality.
Let's now consider a different command:
```
terraformer import aws --regions us-east-1 --profile xxxx \
--filter="Name=vpc_id;Value=xxxx"  \
--resources alb,auto_scaling,cloudformation,dynamodb,ec2_instance,eip,ecs,elb,glue,iam,rds,route53,route_table,s3,sg,subnet,vpc,vpc_peering
```
Terraform will try to apply the attribute filter to get only resources that have field `vpc_id` with value `xxxx` across **all** resource groups, from `subnet `to `alb` to `iam`.

You can further narrow the filter to only specific resource type:
```
terraformer import aws --regions us-east-1 --profile xxxx \
--filter="Type=subnet;Name=vpc_id;Value=xxxx"  \
--resources alb,auto_scaling,cloudformation,dynamodb,ec2_instance,eip,ecs,elb,glue,iam,rds,route53,route_table,s3,sg,subnet,vpc,vpc_peering
```
So that the filter will be applied **only** to `subnet` group.

Hope that will answer your questions. I understand the feature might not be suitable for all cases but I think you will be able to make use of it. I think we must start writing some tutorials with more examples on how to work with this tool, so it will be easier to learn it.

**Comment by julian-alarcon** [comment]
In the README file the example doesn't have the quotation marks. They are needed

Current:
```
terraformer import aws --resources=ec2_instance,ebs --filter=Name=tags.costCenter;Value=20000:'20001:1' --regions=eu-west-1
```
Right way:
```
terraformer import aws --resources=ec2_instance,ebs --filter="Name=tags.costCenter;Value=20000:'20001:1'" --regions=eu-west-1
```

**Comment by meshuga** [comment]
Thanks @julian-alarcon !

**Comment by DFuller134** [comment]
> @ssanbeg To answer your concern, you can filter any resource by its resulting Terraform resource attributes. An example of an AWS resource [aws_lambda_function](https://www.terraform.io/docs/providers/aws/r/lambda_function.html):
> 
> ```
> resource "aws_lambda_function" "lambda_function_id" {
>   environment {
>     variables = {
>       SCHEDULE_HOURS = "1"
>     }
>   }
>   runtime = "java8"
>   tags = {
>     "lambda:createdBy" = "SAM"
>   }
>  ...
> }
> ```
> 
> To get only that Lambda function, you can issue the following commands:
> 
> * `terraformer import  aws --resources=lambda --filter="Name=environment.variables.SCHEDULE_HOURS;Value=1" --regions=ap-southeast-1 ` - to filter all resources by nested path `environment.variables.SCHEDULE_HOURS` with value `1`
> * `terraformer import  aws --resources=lambda --filter="Name=runtime;Value=java8" --regions=ap-southeast-1 ` - to filter all resources by simple path `runtime` with value `java8`
> * `terraformer import  aws --resources=lambda --filter=aws_lambda_function=lambda_function_id --regions=ap-southeast-1` - to filter `aws_lambda_function` resources by its id `lambda_function_id`
> 

I am unable to filter api_gateway resources. I followed the 3rd example in an attempt to filter a specific AWS API Gateway by its ID as follows:

resource "aws_api_gateway_rest_api" "tfer--08tqqu1n6a_PetStore" {
  api_key_source               = "HEADER"
  description                  = "Your first API with Amazon API Gateway. This is a sample API that integrates via HTTP with our demo Pet Store endpoints"
  disable_execute_api_endpoint = "false"

  endpoint_configuration {
    types = ["REGIONAL"]
  }

  minimum_compression_size = "-1"
  name                     = "PetStore"
}


COMMAND:
terraformer import aws --resources=api_gateway --filter=aws_api_gateway_rest_api=tfer--08tqqu1n6a_PetStore --profile=saml

Note that I also attempted filtering for a lambda_function to see if the problem was isolated to aws_api_gateway_rest_api and, while a filter was applied, it only resulted in the generation of lambda_event_source_mapping.tf, outputs.tf, provider.tf, and terraform.tfstate files.
