### ISSUE TITLE
AWS provider: separate SG rules from SGs

### ISSUE THREAD

**Issue by meshuga** [GoogleCloudPlatform/terraformer#493]
The task is to allow terraformer not to inline rules and import them separately.

Ref: https://github.com/GoogleCloudPlatform/terraformer/issues/275#issuecomment-613440892

**Comment by iwasnobody** [comment]
I'm looking forward this feature cause part of aws resources are created manually and part of are managed terraform.
We are now trying to migrate resources created manually to terraform using terraformer.
Cause there is no good way to combine the state file created by terraformer with the our existing state file. We have to use terraform import to add state entry for each resources created by terraformer into the existing state file.
Because the terraform import command import the security group by separate sg rule while the tf config generated by terraformer has inline rules. When I do terraform plan, the separate sg rule will be deleted because they are in state file but not in tf config.
We use terraform enterprise and support engineer in terraform confirmed it is the behavior of terraform import because separate sg rule is their best practice.
<img width="816" alt="Screen Shot 2020-06-18 at 9 47 12 AM" src="https://user-images.githubusercontent.com/20101997/84968290-b7584b00-b148-11ea-91e7-87d2134f5cd1.png">
<img width="800" alt="Screen Shot 2020-06-18 at 9 46 47 AM" src="https://user-images.githubusercontent.com/20101997/84968296-ba533b80-b148-11ea-9543-4e5af24ab705.png">

**Comment by meshuga** [comment]
Thanks for digging that problem! The initial idea was to keep things clear and readable but there are already several people who are asking for the change.

I think the best option in here would be to allow separation of rules from security groups.

**Comment by bmj8409** [comment]
Should this be revisited now that Terraform has yet another way to define the rule resources.....

`aws_vpc_security_group_ingress_rule`
