### ISSUE TITLE
Make generated resource files consistent between each terraformer import runs

### ISSUE THREAD

**Issue by chenrui333** [GoogleCloudPlatform/terraformer#526]
Currently, my issue with running `terraformer import fastly -r service_v1` does not produce consistent output within the resource files, I wonder if we can make it more consistent.

The tfstate file is pretty consistent across the code generations.

**Comment by chenrui333** [comment]
## Example output for `fastly_service_acl_entries_v1` 

### 1st run

```
resource "fastly_service_acl_entries_v1" "tfer--2zHUqDTHvmQYp3KwPbNFC3" {
  acl_id = "2zHUqDTHvmQYp3KwPbNFC3"

  entry {
    comment = "comment1"
    id      = "2vSSprV4crQjimcGtj79zM"
    ip      = "1xx.x.x.x"
    negated = "false"
  }

  entry {
    comment = "comment2"
    id      = "4UYRJmie9aDnQGQRRsedMF"
    ip      = "2.x.x.x"
    negated = "false"
  }
```

### 2nd run

```
resource "fastly_service_acl_entries_v1" "tfer--2zHUqDTHvmQYp3KwPbNFC3" {
  acl_id = "2zHUqDTHvmQYp3KwPbNFC3"

  entry {
    comment = "comment2"
    id      = "4UYRJmie9aDnQGQRRsedMF"
    ip      = "2.x.x.x"
    negated = "false"
  }

  entry {
    comment = "comment1"
    id      = "2vSSprV4crQjimcGtj79zM"
    ip      = "1xx.x.x.x"
    negated = "false"
  }
```

**Comment by mcdir** [comment]
look like this https://github.com/GoogleCloudPlatform/terraformer/issues/342
I have the same issue. 
if someone can tell how this can be done, I could try to implement this.

**Comment by sergeylanzman** [comment]
We save resources in Golang map.
Go map by default not sorted.

Maybe need add sort before generate to files

**Comment by aamarques** [comment]
Hey.. Same issue. Is there a solution?

**Comment by nyetsche** [comment]
I'd also love to see this solved, it'd make Terraformer really using for doing diffs.

To be clear, looking at a few runs over the same resources, I think the resource arguments are stable (sorted alphabetically). It's the value of an argument, such a list or map, or multiple arguments that aren't consistently sorted.

Examples of arguments that change:

```
resource "google_compute_instance" "tfer--gcp-"
   service_account {
     email  = "QQQQQ"
-    scopes = ["https://www.googleapis.com/auth/monitoring.write", "https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/servicecontrol", "https://www.googleapis.com/auth/service.management.readonly", "https://www.googleapis.com/auth/devstorage.read_write", "https://www.googleapis.com/auth/trace.append"]
+    scopes = ["https://www.googleapis.com/auth/service.management.readonly", "https://www.googleapis.com/auth/monitoring.write", "https://www.googleapis.com/auth/servicecontrol", "https://www.googleapis.com/auth/devstorage.read_write", "https://www.googleapis.com/auth/trace.append", "https://www.googleapis.com/auth/logging.write"]
   }

-  tags = ["n", "v", "a", "vpn"]
+  tags = ["v", "n", "vpn", "a"]
   zone = "us-east4-c"
}
```

```
resource "google_storage_default_object_acl" "tfer--test" {
-  role_entity = ["OWNER:project-editors-QQQQ", "OWNER:project-owners-QQQQ", "READER:project-viewers-QQQQ"]
+  role_entity = ["READER:project-viewers-QQQQ", "OWNER:project-editors-QQQQ", "OWNER:project-owners-QQQQ"]
```


```
resource "google_compute_firewall" "tfer--default-002D-allow-002D-internal" {
   allow {
     ports    = ["0-65535"]
-    protocol = "tcp"
+    protocol = "udp"
   }

   allow {
-    ports    = ["0-65535"]
-    protocol = "udp"
+    protocol = "icmp"
   }

   allow {
-    protocol = "icmp"
+    ports    = ["0-65535"]
+    protocol = "tcp"
   }
```

Reading through the code, it looks like JSON is written first and then converted to HCL. Perhaps solving this during JSON output will fix both.

https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraformutils/hcl.go#L134 calling https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraformutils/json.go#L15 (`json.MarshalIndent`)

The JSON marshaller already does sorting of keys, but as I showed earlier it doesn't sort the values after sorting keys:

https://golang.org/pkg/encoding/json/#Marshal:

```
Map values encode as JSON objects. The map's key type must either be a string, an integer type, or implement encoding.TextMarshaler. The map keys are sorted and used as JSON object keys by applying the following rules, ...
```

Interestingly, `fmt` since Go 1.12 should sort maps by key and then value:
https://github.com/golang/go/issues/21095
https://tip.golang.org/doc/go1.12#fmt

But I experimented with `fmt.PrintLn(res.Item)` in `HclPrintResource` section but it didn't consistenly sort keys then values.

There's also an open issue with the encoding/json package related to sorting: https://github.com/golang/go/issues/27179. Perhaps the solution at https://github.com/golang/go/issues/27179#issuecomment-587528269 would work.

**Comment by aamarques** [comment]
Up.

**Comment by mcdir** [comment]
up

**Comment by dmitrievav** [comment]
up

**Comment by kabochkov** [comment]
up

**Comment by aamarques** [comment]
up..

**Comment by mcdir** [comment]
up

**Comment by aamarques** [comment]
Up up up
Is this solved ? I think not!
