### ISSUE TITLE
Filtering route53 resources documentation

### ISSUE THREAD

**Issue by Mallear** [GoogleCloudPlatform/terraformer#69]
Hello,

I struggled to understand how to use filters with aws route53 resources. It may be useful to write somewhere how to fetch hosted zone IDs (with aws-cli but whithout the `/hostedzone/` part) and that records ID are made of  `<hosted zone id>_<fqdn>_<record type>`.

I can make a PR if you tell me where this documentation belongs.

**Comment by sergeylanzman** [comment]
Yes it's filtered by terraform ID. Same ID use in terraform import command or in tfstate.
Because each resource in any providers has other pattern for ID, it's complicate. 
I be happy if you send PR with  new documentation, but need describe general pattern(terraform ID), not only route53
https://www.terraform.io/docs/providers/aws/r/route53_record.html#import
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/route53.go#L73

**Comment by Mallear** [comment]
Made a PR ( #71 ) for filtering documentation. I hope it will be clear  enough.

May I suggest considering replacing `resource` key word by `service` and `filter` by `resource` to make it clearer ?
