### ISSUE TITLE
Comparison w/ terraforming project

### ISSUE THREAD

**Issue by mwarkentin** [GoogleCloudPlatform/terraformer#80]
I see that you link to it as a similar project, but it would be helpful to understand what the pros/cons of terraformer vs. terraforming would be for a user.

**Comment by sergeylanzman** [comment]
Terraforming it's good project, but I think with bad idea. Terraforming get all attributes from cloud API and create hcl  tfstate files with templating. Each attribute in API need to map to attribute in terraform. Each time when provider add new attribute need change code of terraforming. It's endless work.
Creating hcl files with templating sometimes breaking, without illegal syntax.
Terraforming support only AWS because it's very complicate add new resources or providers.
Look for S3 support in Terraforming here and official s3 support
terraforming - https://github.com/dtan4/terraforming/blob/master/lib/terraforming/template/tf/s3.erb
official s3 support - https://www.terraform.io/docs/providers/aws/r/s3_bucket.html
You can see 70% of s3 options not supported.

Terraformer use terraform provider files for mapping attributes + hcl library from hashicorp + terraform code + many magics.
Results:
1. More simple add new provider or resources - today support AWS, GCP, Github, Kubernetes, Openstack. 
2. Better full support HCL + tfstate, include 0.12
3. If cloud provider add new attributes to resource, no need change Terraformer code. only update terraform provider in your laptop. 
4. "Magic" - support connect between resources in hcl files and etc.

**Comment by mwarkentin** [comment]
Thanks, that’s very helpful! Do you think it’s worth summarizing the same in the readme?

**Comment by pchaganti** [comment]
This is a really helpful summary. Thanks!

**Comment by sergeylanzman** [comment]
@mwarkentin
I think about add to readme the summary, but with better english..
Maybe you want send PR with this content? in "Similar projects"

**Comment by mwarkentin** [comment]
Sure, I can open a PR.

**Comment by mwarkentin** [comment]
@sergeylanzman opened #83
