### ISSUE TITLE
Missing aws_iam_group_policy_attachment for customer managed policy

### ISSUE THREAD

**Issue by raeder1986** [GoogleCloudPlatform/terraformer#901]
Good day! During testing of Terraformer we created a Custom managed policy using AWS portal and added it to IAM group with a couple of users. Also we had another AWS managed policies attached to this group. But, after running 

_terraformer import aws --resources=iam_

we got in aws_iam_group_policy_attachment.tf only attachments for AWS managed policies, and no for Customer managed.

Terraformer version v0.8.13

**Comment by meshuga** [comment]
Thanks for pointing this out!

According to the TF docs, `aws_iam_group_policy_attachment ` is for Managed IAM Policies (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group_policy_attachment).

I wrongly read this and thought it's only for AWS Managed policies but it's for attaching all policies to a group. Should have it fixed in #845

**Comment by 96nico** [comment]
Hi @meshugam I'm having the same issue using Terraformer v0.8.22
