### ISSUE TITLE
"aws aws_network_interface" "interface_type" expects "efa" "branch" or "trunk" not "load_balancer" "interface" or "nat_gateway" ?

### ISSUE THREAD

**Issue by vainkop** [GoogleCloudPlatform/terraformer#973]
Hi. So I've parsed some AWS infra with Terraformer 0.8.14 (latest atm) using aws provider 3.47.0 (also latest atm) & got some ENIs but when I try to run terraform init + plan on them (0.13.7) I see 3 types of errors:

`load_balancer`, `interface` & `nat_gateway` instead of `efa`, `branch` or `trunk` expected by Terraform in `aws_network_interface` resource

```
Error: expected interface_type to be one of [efa branch trunk], got load_balancer

  on network_interface.tf line 27, in resource "aws_network_interface" "tfer--eni-002D-013edaa0":
  27:   interface_type     = "load_balancer"
```

```
Error: expected interface_type to be one of [efa branch trunk], got interface

  on network_interface.tf line 39, in resource "aws_network_interface" "tfer--eni-002D-01a6579e8afff14b4":
  39:   interface_type     = "interface"
```

```
Error: expected interface_type to be one of [efa branch trunk], got nat_gateway

  on network_interface.tf line 717, in resource "aws_network_interface" "tfer--eni-002D-9d18d28b":
 717:   interface_type     = "nat_gateway"
```

And then I check the AWS console & see that those types are real (see screenshots).

Is it a bug in Terraformer?

Should I pin the aws provider for it to different version (but I'm doing terraform init for terraformer first & for the resulting code & I can see same aws provider version 3.47.0 used so they match) ?

Am I missing something here?

![image](https://user-images.githubusercontent.com/28118190/124003223-5ca23200-d9df-11eb-8329-a621975e1054.png)
![image](https://user-images.githubusercontent.com/28118190/124003247-6166e600-d9df-11eb-9553-0424f1092801.png)
![image](https://user-images.githubusercontent.com/28118190/124003264-64fa6d00-d9df-11eb-94e9-210cda468469.png)

**Comment by paulegradie** [comment]
Really? No guidence or on this?

**Comment by sajithpvivi** [comment]
This is what I found

**EFA - I believe it's the normal interface**
https://awscli.amazonaws.com/v2/documentation/api/2.3.2/reference/ec2/create-network-interface.html

Indicates the type of network interface. To create an Elastic Fabric Adapter (EFA), specify efa . For more information, see [Elastic Fabric Adapter](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html) in the Amazon Elastic Compute Cloud User Guide . To create a trunk network interface, specify efa . For more information, see [Network interface trunking](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/eni-trunking.html) in the Amazon Elastic Compute Cloud User Guide .


**TRUNK is for ECS/Task Definitions**
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/container-instance-eni.html

Amazon ECS supports launching container instances with increased ENI density using supported Amazon EC2 instance types. When you use these instance types and opt in to the awsvpcTrunking account setting, additional ENIs are available on newly launched container instances. This configuration allows you to place more tasks using the awsvpc network mode on each container instance. Using this feature, a c5.large instance with awsvpcTrunking enabled has an increased ENI limit of twelve. The container instance will have the primary network interface and Amazon ECS creates and attaches a "trunk" network interface to the container instance. So this configuration allows you to launch ten tasks on the container instance instead of the current two tasks.

**interfaceType**
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_NetworkInterface.html

The type of network interface.

Type: String

Valid Values: interface | natGateway | efa | trunk | load_balancer | network_load_balancer | vpc_endpoint | branch | transit_gateway | lambda | quicksight | global_accelerator_managed | api_gateway_managed | gateway_load_balancer | gateway_load_balancer_endpoint | iot_rules_managed | aws_codestar_connections_managed

**Comment by mnedelko** [comment]
Agree this item should be reopened.

**Comment by evbo** [comment]
This is a bug with terraform itself, please +1 this issue to get more momentum in solving it:
https://github.com/hashicorp/terraform-provider-aws/issues/33857
